name: Update README

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update README
        run: |
          REPO_COUNT=$(curl -s https://api.github.com/users/Aryanrathod21 | jq .public_repos)
          sed -i "s/<your_repo_count>/$REPO_COUNT/" README.md
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update repository count'
          git push
